/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dlaidlaw' at '12/17/16 12:15 PM' with Gradle 2.14
 *
 * @author dlaidlaw, @date 12/17/16 12:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
